project:
  type: website

website:
  title: "coco"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/boram-coco

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true