project:
  type: website

website:
  title: "coco"
  
  page-footer:
    border: true
    
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/boram-coco
      - icon: lightning
        href: https://icons.getbootstrap.com/

  sidebar:
    style: "docked"
    search: true
    contents:
      - Note.qmd
      - GNN.qmd
      - Synthetic.qmd
      - Study.qmd
format:
  html:
    theme: cosmo
    css: styles.css
